changelog:
  categories:
    - title: GovernSeed Breaking Changes
      labels:
        - breaking
        - breaking-change
    - title: GovernSeed Features
      labels:
        - feature
        - enhancement
    - title: GovernSeed Fixes
      labels:
        - fix
        - bug
    - title: GovernSeed Docs
      labels:
        - docs
        - documentation
    - title: GovernSeed Maintenance
      labels:
        - maintenance
        - chore
        - ci
    - title: Other GovernSeed Changes
      labels:
        - "*"
